name: frontend
type: 'php:8.2'  # We use PHP but won't actually need it, as Platform.sh requires a runtime.

build:
    flavor: none  # No build step is needed since it's a static site.

size: XS  # Smallest size for minimal resource consumption.

web:
    commands:
        start: sleep  # No need to start any services, since it's a static site.
    locations:
        "/":
            root: "public"  # Change this to the folder where your static assets are located.
            index:
                - "index.html"
            scripts: false  # No PHP scripting required.
            expires: 10m  # Cache static assets for 10 minutes.

disk: 256  # 256 MB of disk space, as a static front-end doesn't need much.