# Utiliser PHP 8.2 comme image de base
FROM php:8.2-cli

# Installer les dépendances système nécessaires pour Symfony et PHP
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    libzip-dev \
    unzip \
    git \
    curl \
    libicu-dev \
    libxml2-dev \
    zlib1g-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd pdo pdo_mysql zip intl xml

# Installer Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Définir un dossier de travail
WORKDIR /var/www/html

# Autoriser Composer à s'exécuter en super utilisateur
ENV COMPOSER_ALLOW_SUPERUSER=1

# Copier les fichiers composer
COPY composer.json composer.lock ./

# Configurer le cache de Composer pour éviter les erreurs de permission
RUN composer config --global cache-dir /tmp/composer-cache

# Ajuster les permissions sur le répertoire de travail pour éviter les erreurs
RUN chown -R www-data:www-data /var/www/html

# Passer temporairement à l’utilisateur root pour exécuter composer install
USER root

# Installer les dépendances sans dépendances de développement
RUN composer clear-cache && composer install --no-dev --optimize-autoloader --no-interaction --no-progress

# Copier le reste des fichiers de l'application dans le conteneur
COPY . /var/www/html

# Ajuster les permissions une nouvelle fois pour l’utilisateur www-data
RUN chown -R www-data:www-data /var/www/html

# Revenir à l’utilisateur www-data pour éviter les permissions root
USER www-data

# Exposer le port
EXPOSE 9000

# Démarrer l'application Symfony
CMD ["php", "-S", "0.0.0.0:9000", "-t", "public"]
