nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_credentials: true
        allow_methods: ['POST','PUT', 'GET', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-AUTH-TOKEN']
        expose_headers: []
        max_age: 3600
        origin_regex: false
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600