nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000', 'http://localhost']
        allow_credentials: true
        allow_methods: ['POST', 'GET', 'OPTIONS', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: []
        max_age: 3600
        origin_regex: false
    paths:
        '^/api/':
            allow_origin: ['http://localhost:3000', 'http://localhost']
            allow_methods: ['POST', 'GET', 'OPTIONS', PUT', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
